import fs from "node:fs";
import path from "node:path";
import type { Workpaper } from "./types.js";
import { saveOriginalDrafts } from "./diff-tracker.js";

export function renderWorkpaper(workpaper: Workpaper): string {
  const lines: string[] = [];

  lines.push(`# Audit Workpaper: ${workpaper.systemName}`);
  lines.push("");
  lines.push(`**System:** ${workpaper.systemFile}  `);
  lines.push(`**Workpaper ID:** ${workpaper.id}  `);
  lines.push(`**Status:** ${workpaper.status.toUpperCase()}  `);
  lines.push(`**Created:** ${workpaper.createdAt.slice(0, 10)}  `);
  lines.push(`**Updated:** ${workpaper.updatedAt.slice(0, 10)}  `);
  if (workpaper.reviewedBy) {
    lines.push(`**Reviewed by:** ${workpaper.reviewedBy}  `);
  }
  if (workpaper.approvedBy) {
    lines.push(`**Approved by:** ${workpaper.approvedBy}  `);
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  // Table of contents
  lines.push("## Table of Contents");
  lines.push("");
  for (let i = 0; i < workpaper.sections.length; i++) {
    const section = workpaper.sections[i];
    const anchor = section.title.toLowerCase().replace(/\s+/g, "-");
    lines.push(`${i + 1}. [${section.title}](#${anchor})`);
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  // Sections
  for (const section of workpaper.sections) {
    lines.push(`## ${section.title}`);
    lines.push("");
    lines.push(section.content);
    lines.push("");

    // Provenance footer for AI-generated sections
    if (section.provenance) {
      lines.push("---");
      lines.push("");
      lines.push(
        `*AI-generated (${section.provenance.model}, ` +
          `${section.provenance.cached ? "cached" : "fresh"}, ` +
          `${section.provenance.tokenCount.prompt + section.provenance.tokenCount.completion} tokens). ` +
          `This section is a DRAFT — human review required before approval.*`
      );
      lines.push("");
    }
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push(
    "*Generated by [workpapr](https://workpapr.ai). " +
      "All AI-generated content is in DRAFT status and requires human review before approval.*"
  );
  lines.push("");

  return lines.join("\n");
}

export function saveWorkpaper(
  rootDir: string,
  workpaper: Workpaper
): string {
  const dir = path.join(rootDir, ".workpapr", "workpapers");
  fs.mkdirSync(dir, { recursive: true });

  const sanitizedName = workpaper.systemName
    .replace(/[/\\]/g, "-")
    .replace(/[^a-zA-Z0-9_-]/g, "");
  const fileName = `${sanitizedName}.md`;
  const filePath = path.join(dir, fileName);

  const content = renderWorkpaper(workpaper);
  fs.writeFileSync(filePath, content, "utf-8");

  // Save original AI drafts for training data capture (diff tracking)
  const aiSections = workpaper.sections.filter((s) => s.provenance);
  if (aiSections.length > 0) {
    saveOriginalDrafts(rootDir, workpaper.id, aiSections);
  }

  return path.relative(rootDir, filePath);
}

export function saveWorkpaperIndex(
  rootDir: string,
  workpapers: Workpaper[]
): string {
  const dir = path.join(rootDir, ".workpapr", "workpapers");
  fs.mkdirSync(dir, { recursive: true });

  const lines: string[] = [];
  lines.push("# Audit Workpapers Index");
  lines.push("");
  lines.push(`Generated: ${new Date().toISOString().slice(0, 10)}`);
  lines.push("");
  lines.push("| System | File | Status | Findings | Workpaper |");
  lines.push("|--------|------|--------|----------|-----------|");

  for (const wp of workpapers) {
    const sanitizedName = wp.systemName
      .replace(/[/\\]/g, "-")
      .replace(/[^a-zA-Z0-9_-]/g, "");
    const fileName = `${sanitizedName}.md`;
    const findingCount = wp.sections
      .find((s) => s.id === "risk-assessment")
      ?.content.split("\n")
      .filter((l) => l.startsWith("|") && !l.includes("---") && !l.includes("Severity"))
      .length ?? 0;

    lines.push(
      `| ${wp.systemName} | ${wp.systemFile} | ${wp.status.toUpperCase()} | ${findingCount} | [${fileName}](./${fileName}) |`
    );
  }

  lines.push("");
  lines.push(
    "*All workpapers are in DRAFT status until reviewed and approved by an authorized auditor.*"
  );
  lines.push("");

  const filePath = path.join(dir, "index.md");
  fs.writeFileSync(filePath, lines.join("\n"), "utf-8");

  return path.relative(rootDir, filePath);
}
